import React, { useState, useEffect } from 'react';
import { Modal, Button, ListGroup, Alert } from 'react-bootstrap';
import { getAttendanceById } from '@/actions/attendance';
import generateCertificate from "@/utils/generateCertificate";
import { jsPDF } from 'jspdf';
import 'jspdf-autotable'; // Required for table creation

const AttendanceModal = ({ attendanceId, showModal, handleClose }) => {
  const [attendance, setAttendance] = useState(null);
  const [error, setError] = useState(null);

  // Fetch the attendance record by ID when the modal opens
  useEffect(() => {
    if (attendanceId && showModal) {
      const fetchAttendance = async () => {
        try {
          const data = await getAttendanceById(attendanceId);
          setAttendance(data);
        } catch (err) {
          setError('Failed to load attendance record.');
          console.error('Error fetching attendance:', err);
        }
      };
      fetchAttendance();
    }
  }, [attendanceId, showModal]);

  const handleDownloadPDF = () => {
    if (!attendance) {
      return;
    }

    const doc = new jsPDF({ compress: true });

    // Format Group Name
    const formattedGroup = attendance.group
      ? attendance.group.replace(/_/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase())
      : 'N/A';

    // Get Current Date and Time
    const currentDate = new Date();
    const formattedDate = currentDate.toLocaleDateString();
    const formattedTime = currentDate.toLocaleTimeString();

    // Add Header Section with Purple Theme
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(128, 0, 128); // Purple color
    doc.setFontSize(20);
    doc.text('KKKT USHARIKA WA YOMBO', 105, 15, { align: 'center' });

    doc.setFontSize(14);
    doc.text(`Kikundi: ${formattedGroup}`, 14, 30); // Group Name
    doc.text(`Tarehe ya ${attendance.session_name}: ${new Date(attendance.date).toLocaleDateString()}`, 14, 40);

    // Add Attendees Table with Ratings
    const headers = ['#', 'Jina la Mshiriki', 'Alama'];
    const body = attendance.attendees.map((attendee, index) => [
      index + 1,
      attendee.name,
      attendee.cumulativeRating || 'N/A', // Show cumulative rating or 'N/A' if not available
    ]);

    doc.autoTable({
      head: [headers],
      body: body,
      startY: 50,
      theme: 'grid',
      headStyles: {
        fillColor: [128, 0, 128], // Purple background
        textColor: [255, 255, 255], // White text
      },
      styles: {
        fontSize: 10,
        cellPadding: 3,
      },
      alternateRowStyles: {
        fillColor: [240, 230, 250], // Light purple for alternate rows
      },
    });

    // Add Footer Section
    const pageHeight = doc.internal.pageSize.height;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
   
    doc.setTextColor(128, 0, 128); // Purple color for footer phrase
    doc.text('Generated by Usharika wa Yombo System', 105, pageHeight - 10, { align: 'center' });

    // Save the PDF with a filename
    const sanitizedGroupName = formattedGroup.replace(/[^\w-]/g, '_');
    doc.save(`${sanitizedGroupName}_mahudhurio.pdf`);
  };

  if (!attendance && !error) {
    return null; // Return null if no attendance data is available yet
  }

  return (
    <Modal show={showModal} onHide={handleClose}>
      <Modal.Header closeButton>
        <Modal.Title>{attendance ? attendance.session_name : 'Loading...'}</Modal.Title>
      </Modal.Header>
      <Modal.Body>
        {error ? (
          <Alert variant="danger">{error}</Alert>
        ) : (
          <>
            <h5>Tarehe: {new Date(attendance.date).toLocaleDateString()}</h5>
            <ListGroup>
              <ListGroup.Item>
                <strong>Kikundi:</strong> {attendance.group}
              </ListGroup.Item>
              <ListGroup.Item>
                <strong>Waliohudhuria:</strong>
                <ListGroup>
                  {attendance.attendees.map((attendee) => (
                    <ListGroup.Item key={attendee.userId}>
                      <strong>{attendee.name}</strong> - Alama: {attendee.cumulativeRating || 'N/A'}
                    </ListGroup.Item>
                  ))}
                </ListGroup>
              </ListGroup.Item>
            </ListGroup>
          </>
        )}
      </Modal.Body>
      <Modal.Footer>
        <Button variant="primary" onClick={handleDownloadPDF}>
          Pakua PDF
        </Button>
       
      </Modal.Footer>
    </Modal>
  );
};

export default AttendanceModal;
