'use client';

import React, { useEffect, useState } from "react";
import { FaTrophy, FaMedal, FaAward, FaDownload, FaCertificate, FaCalendarAlt } from "react-icons/fa";
import { getTopRankingUsers } from "@/actions/users";
import generateCertificate from "@/utils/certificate";
import { jsPDF } from "jspdf";
import 'jspdf-autotable';

const TopRankingUsers = ({ group }) => {
  const [topUsers, setTopUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [interval, setInterval] = useState(7);
  const [dateRange, setDateRange] = useState({ startDate: "", endDate: "" });

  useEffect(() => {
    const fetchTopUsers = async () => {
      try {
        setLoading(true);
        setError(null);
        const data = await getTopRankingUsers({ group, interval });
        setTopUsers(data);
      } catch (err) {
        setError(err.message || "Failed to fetch top-ranking users.");
      } finally {
        setLoading(false);
      }
    };

    fetchTopUsers();
  }, [group, interval]);

  useEffect(() => {
    const calculateDateRange = () => {
      const currentDate = new Date();
      const startDate = new Date(currentDate);
      startDate.setDate(currentDate.getDate() - interval);

      const options = { year: 'numeric', month: 'long', day: 'numeric' };
      const formattedStartDate = startDate.toLocaleDateString("sw-TZ", options);
      const formattedEndDate = currentDate.toLocaleDateString("sw-TZ", options);

      setDateRange({ startDate: formattedStartDate, endDate: formattedEndDate });
    };

    calculateDateRange();
  }, [interval]);

  const handleIntervalChange = (e) => {
    setInterval(Number(e.target.value));
  };

  const handleCertificateGeneration = () => {
    if (topUsers.length > 0) {
      const maxPoints = Math.max(...topUsers.map(user => user.cumulativeRating));
      const topUsersWithSamePoints = topUsers.filter(user => user.cumulativeRating === maxPoints);

      topUsersWithSamePoints.forEach((user) => {
        const recipientDetails = {
          recipientName: user.name || "Anonymous User",
          points: user.cumulativeRating,
          groupName: group,
          interval,
          dateRange,
          issuer: group
        };
        generateCertificate(recipientDetails);
      });
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const formattedGroup = group === "kwaya_vijana" ? "Kwaya ya Vijana" : group;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text(`${formattedGroup}`, 105, 25, { align: 'center' });

    doc.setFontSize(14);
    doc.text('Msimamo wa Umahiri wa Kutunza Muda', 105, 15, { align: 'center' });

    doc.setFontSize(12);
    doc.text(`Kuanzia: ${dateRange.startDate} mpaka ${dateRange.endDate}`, 105, 35, { align: 'center' });

    const headers = ['#', 'Jina', 'Alama'];
    const body = topUsers.map((user, index) => [
      index + 1,
      user.name || 'Anonymous User',
      user.cumulativeRating || 'N/A',
    ]);

    doc.autoTable({
      head: [headers],
      body: body,
      startY: 45,
      theme: 'grid',
      headStyles: {
        fillColor: [107, 70, 193],
        textColor: [255, 255, 255],
      },
      styles: {
        fontSize: 10,
        cellPadding: 3,
      },
      alternateRowStyles: {
        fillColor: [240, 230, 250],
      },
    });

    const pageHeight = doc.internal.pageSize.height;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(10);
    doc.setTextColor(107, 70, 193);
    doc.text('Generated by KKKT Yombo Usharika wa Yombo System', 105, pageHeight - 10, { align: 'center' });

    doc.save(`chati_ya_umahiri_${group}.pdf`);
  };

  const getRankIcon = (index) => {
    switch (index) {
      case 0:
        return <FaTrophy className="text-yellow-500 text-xl" />;
      case 1:
        return <FaMedal className="text-gray-400 text-xl" />;
      case 2:
        return <FaAward className="text-yellow-600 text-lg" />;
      default:
        return <div className="w-5 h-5 rounded-full bg-primary-200 flex items-center justify-center text-xs font-bold text-primary-700">{index + 1}</div>;
    }
  };

  const getRankBadge = (index) => {
    const badges = {
      0: "bg-gradient-to-r from-yellow-400 to-yellow-600 text-white",
      1: "bg-gradient-to-r from-gray-300 to-gray-500 text-white", 
      2: "bg-gradient-to-r from-yellow-600 to-yellow-800 text-white"
    };
    return badges[index] || "bg-primary-100 text-primary-700";
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-background-50 via-background-100 to-background-300 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-4 border-primary-200 border-t-primary-600 mx-auto mb-4"></div>
          <p className="text-text-secondary font-medium">Inapakia...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-background-50 via-background-100 to-background-300 flex items-center justify-center px-4">
        <div className="bg-error-50 border border-error-200 rounded-2xl p-6 max-w-md w-full text-center">
          <div className="text-error-500 text-2xl mb-4">⚠️</div>
          <p className="text-error-700 font-medium">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background-50 via-background-100 to-background-300">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Header */}
        <div className="text-center mb-8 animate-fade-in">
          <h1 className="text-4xl font-display font-bold text-text-primary mb-4">
            Wanakikundi Bora
          </h1>
          <p className="text-text-secondary text-lg">
            Msimamo wa umahiri wa kutunza muda
          </p>
        </div>

        {/* Main Card */}
        <div className="glass backdrop-blur-xl rounded-3xl shadow-strong overflow-hidden animate-slide-up">
          {/* Card Header */}
          <div className="bg-primary-gradient px-8 py-6">
            <div className="flex items-center justify-center space-x-3">
              <FaTrophy className="text-yellow-300 text-2xl animate-gentle-float" />
              <h2 className="text-2xl font-display font-bold text-white text-shadow">
                Chati ya Alama
              </h2>
            </div>
          </div>

          {/* Controls Section */}
          <div className="bg-white/90 backdrop-blur-sm px-8 py-6 border-b border-border-light">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between space-y-4 sm:space-y-0">
              {/* Date Range Display */}
              <div className="flex items-center space-x-2 text-text-secondary">
                <FaCalendarAlt className="text-primary-500" />
                <span className="text-sm font-medium">
                  {dateRange.startDate} - {dateRange.endDate}
                </span>
              </div>

              {/* Interval Input */}
              <div className="flex items-center space-x-3">
                <label htmlFor="interval" className="text-sm font-semibold text-text-primary whitespace-nowrap">
                  Idadi ya Siku:
                </label>
                <input
                  id="interval"
                  type="number"
                  min="1"
                  max="30"
                  value={interval}
                  onChange={handleIntervalChange}
                  className="
                    w-20 px-3 py-2 rounded-xl border-2 border-border-light
                    focus:border-primary-500 focus:ring-4 focus:ring-primary-500/20
                    transition-all duration-300 text-center font-medium
                    bg-background-50 text-text-primary
                  "
                />
              </div>
            </div>
          </div>

          {/* Users List */}
          <div className="bg-white/90 backdrop-blur-sm">
            {topUsers.length === 0 ? (
              <div className="px-8 py-12 text-center">
                <div className="text-6xl mb-4">🏆</div>
                <p className="text-text-secondary font-medium">
                  Hakuna kipindi kilichorekodiwa kwa siku hizi
                </p>
              </div>
            ) : (
              <div className="divide-y divide-border-light">
                {topUsers.map((user, index) => (
                  <div
                    key={user.userId}
                    className={`
                      px-8 py-6 flex items-center justify-between transition-all duration-300
                      hover:bg-primary-50/50 group
                      ${index < 3 ? 'bg-gradient-to-r from-primary-50/30 to-transparent' : ''}
                    `}
                  >
                    {/* User Info */}
                    <div className="flex items-center space-x-4">
                      <div className="flex-shrink-0">
                        {getRankIcon(index)}
                      </div>
                      <div>
                        <h3 className="font-bold text-text-primary text-lg group-hover:text-primary-700 transition-colors">
                          {user.name || "Anonymous User"}
                        </h3>
                        <p className="text-text-secondary text-sm">
                          Alama zilizokusanywa: {user.cumulativeRating}
                        </p>
                      </div>
                    </div>

                    {/* Rank Badge */}
                    <div className={`
                      px-4 py-2 rounded-full text-sm font-bold transition-all duration-300
                      ${getRankBadge(index)}
                      group-hover:scale-105
                    `}>
                      #{index + 1}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Action Buttons */}
            {topUsers.length > 0 && (
              <div className="px-8 py-6 bg-background-100 border-t border-border-light">
                <div className="flex flex-col sm:flex-row space-y-3 sm:space-y-0 sm:space-x-4 justify-center">
                  <button
                    onClick={handleCertificateGeneration}
                    className="
                      btn-success px-6 py-3 rounded-2xl text-white font-bold text-sm
                      flex items-center justify-center space-x-3
                      shadow-green-lg hover:shadow-green-lg
                      transition-all duration-300
                    "
                  >
                    <FaCertificate className="text-lg" />
                    <span>Pata Cheti kwa Mhudhuriaji Bora</span>
                  </button>
                  
                  <button
                    onClick={handleDownloadPDF}
                    className="
                      btn-secondary px-6 py-3 rounded-2xl text-white font-bold text-sm
                      flex items-center justify-center space-x-3
                      shadow-yellow-lg hover:shadow-yellow-lg
                      transition-all duration-300
                    "
                  >
                    <FaDownload className="text-lg" />
                    <span>Download PDF</span>
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Stats Cards */}
        {topUsers.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8">
            {/* Total Participants */}
            <div className="glass backdrop-blur-sm rounded-2xl p-6 text-center shadow-medium">
              <div className="text-3xl font-bold text-primary-600 mb-2">
                {topUsers.length}
              </div>
              <p className="text-text-secondary font-medium">Washiriki Jumla</p>
            </div>

            {/* Highest Score */}
            <div className="glass backdrop-blur-sm rounded-2xl p-6 text-center shadow-medium">
              <div className="text-3xl font-bold text-yellow-600 mb-2">
                {topUsers[0]?.cumulativeRating || 0}
              </div>
              <p className="text-text-secondary font-medium">Alama za Juu</p>
            </div>

            {/* Average Score */}
            <div className="glass backdrop-blur-sm rounded-2xl p-6 text-center shadow-medium">
              <div className="text-3xl font-bold text-green-600 mb-2">
                {Math.round(topUsers.reduce((sum, user) => sum + user.cumulativeRating, 0) / topUsers.length) || 0}
              </div>
              <p className="text-text-secondary font-medium">Wastani wa Alama</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default TopRankingUsers;